# Configuration for running tool/generate_dart_api.dart
package_mappings:
  - core-: core_elements
  - web-animations: core_elements
files_to_generate:
  - font-roboto/roboto.html
  - paper-button/paper-button.html
  - paper-checkbox/paper-checkbox.html
  - paper-dialog/paper-dialog.html
  - paper-dialog/paper-dialog-transition.html
  - paper-fab/paper-fab.html
  - paper-focusable/paper-focusable.html
  - paper-icon-button/paper-icon-button.html
  - paper-input/paper-input.html
  - paper-ink/paper-ink.html
  - paper-item/paper-item.html
  - paper-menu-button/paper-menu-button.html
  - paper-menu-button/paper-menu-button-overlay.html
  - paper-menu-button/paper-menu-button-transition.html
  - paper-progress/paper-progress.html
  - paper-radio-button/paper-radio-button.html
  - paper-radio-group/paper-radio-group.html
  - paper-ripple/paper-ripple.html
  - paper-shadow/paper-shadow.html
  - paper-slider/paper-slider.html
  - paper-tabs/paper-tab.html
  - paper-tabs/paper-tabs.html
  - paper-toast/paper-toast.html
  - paper-toggle-button/paper-toggle-button.html
  # Skip this for now, it doesn't have APIs and is generated incorrectly.
  #- paper-transition/paper-transition-dialog.html
stubs_to_generate:
  core_elements:
    - core-animation/core-animation.html
    - core-animation/core-animation-group.html
    - core-animation/web-animations.html
    - core-collapse/core-collapse.html
    - core-component-page/core-component-page.html
    - core-drawer-panel/core-drawer-panel.html
    - core-header-panel/core-header-panel.html
    - core-icon/core-icon.html
    - core-icon-button/core-icon-button.html
    - core-icons/core-icons.html
    - core-iconset/core-iconset.html
    - core-iconset-svg/core-iconset-svg.html
    - core-input/core-input.html
    - core-item/core-item.html
    - core-media-query/core-media-query.html
    - core-menu/core-menu.html
    - core-menu/core-submenu.html
    - core-meta/core-meta.html
    - core-overlay/core-key-helper.html
    - core-overlay/core-overlay.html
    - core-overlay/core-overlay-layer.html
    - core-range/core-range.html
    - core-selection/core-selection.html
    - core-selector/core-selector.html
    - core-toolbar/core-toolbar.html
    - core-transition/core-transition.html
    - core-transition/core-transition-css.html
