name: paper_elements
version: 0.7.1+2
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Paper elements for Dart
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  core_elements: '>=0.7.1 <0.8.0'
  polymer_interop: ">=0.1.0+2 <0.2.0"
  web_components: ">=0.9.0 <0.13.0"
dev_dependencies:
  custom_element_apigen: ">= 0.1.7 <0.2.0"
  path: ">=1.0.0 <2.0.0"
  polymer: ">=0.16.1+4 <0.17.0"
  unittest: ">=0.11.0+2 <0.12.0"
  matcher: ">=0.10.1+1 <0.12.0"
transformers:
- polymer:
    entry_points:
      - test/paper_button_test.html
      - test/paper_dropdown_basic_test.html
      - test/paper_fab_a11y_test.html
      - test/paper_fab_basic_test.html
      - test/paper_icon_button_a11y_test.html
      - test/paper_icon_button_basic_test.html
      - test/paper_input_test.html
      - test/paper_input_autogrow_test.html
      - test/paper_input_decorator_test.html
      - test/paper_ripple_position_test.html
      - test/paper_shadow_basic_test.html
    lint:
      exclude: lib/src/
    inline_stylesheets:
      lib/src/paper-shadow/paper-shadow.css: true
- $dart2js:
    $include: "**/*.polymer.bootstrap.dart"
